In [244]:
import pandas as pd
import numpy as np
import random

import matplotlib

In [86]:
# Discounts are offered too frequently, training customers to expect a discount

# multibuy promotions
# Lindahls PRO £1.40 but buy 4 for £3 (not £5.6 and £2.5999 saving)

In [252]:
np.random.seed(41)

dates = pd.date_range(start="2025-01-01", end="2025-01-31") # sequence the whole year

products = ["M&S High Protein Skimmed Milk 1L", 
            "Fage Total 5% Fat Natural Greek Yoghurt 950gr", 
            "Eatlean Protein Cheese Grated 180gr", 
            "Chia Charge Soya Protein Crispies 80% 250gr"]

price1 = [1.60, 1.40, 1.10]
price2 = [5.25, 5.0, 4.5]
price3 = [2.25, 1.69, 1.12]
price4 = [17, 14.90, 11.90]

promotions = [0.10, 0.80, 0.50, .30]
qty = []

data = []

for date in dates:
    for product in products:
        if product == products[0]:
            price = random.choice(price1) # 1.40 is mine, the rest is from Ocado
            promotion = round((1.60-price)/1.60,2)
            units_sold = round(np.random.poisson(lam=30 if promotion != 0 else 15))
            revenue = round(price * units_sold, 2)
            data.append([date, product, price, units_sold, promotion, revenue])
        elif product == products[1]:
            price = random.choice(price2) # Original price 5.5, discounted 4.5, 5 is added by me
            promotion = round((5.5-price)/5.5,2)
            units_sold = round(np.random.poisson(lam=30 if promotion != 0 else 15)) 
            revenue = round(price * units_sold, 2)
            data.append([date, product, price, units_sold, promotion, revenue])
        elif product == products[2]:
            price = random.choice(price3) # Original price 5.5, discounted 4.5, 5 is added by me
            promotion = round((2.25-price)/2.25,2)
            units_sold = round(np.random.poisson(lam=30 if promotion != 0 else 15)) 
            revenue = round(price * units_sold, 2)
            data.append([date, product, price, units_sold, promotion, revenue])
        elif product == products[3]:
            price = random.choice(price4) # Original price 5.5, discounted 4.5, 5 is added by me
            promotion = round((17-price)/17,2)
            units_sold = round(np.random.poisson(lam=30 if promotion != 0 else 15))
            revenue = round(price * units_sold, 2)
            data.append([date, product, price, units_sold, promotion, revenue])

df = pd.DataFrame(data, columns=["Date", "Product", "Price", "Units Sold", "Promotion", "Revenue"])

df

,Date,Product,Price,Units Sold,Promotion,Revenue
0,2025-01-01,M&S High Protein Skimmed Milk 1L,1.40,26,0.13,36.40
1,2025-01-01,Fage Total 5% Fat Natural Greek Yoghurt 950gr,5.00,33,0.09,165.00
2,2025-01-01,Eatlean Protein Cheese Grated 180gr,1.69,22,0.25,37.18
3,2025-01-01,Chia Charge Soya Protein Crispies 80% 250gr,14.90,24,0.12,357.60
4,2025-01-02,M&S High Protein Skimmed Milk 1L,1.10,39,0.31,42.90
...,...,...,...,...,...,...
119,2025-01-30,Chia Charge Soya Protein Crispies 80% 250gr,14.90,32,0.12,476.80
120,2025-01-31,M&S High Protein Skimmed Milk 1L,1.40,32,0.13,44.80
121,2025-01-31,Fage Total 5% Fat Natural Greek Yoghurt 950gr,5.00,47,0.09,235.00
122,2025-01-31,Eatlean Protein Cheese Grated 180gr,1.12,33,0.50,36.96
123,2025-01-31,Chia Charge Soya Protein Crispies 80% 250gr,11.90,33,0.30,392.70

In [ ]:
df[df['Product'] == product[0]

In [ ]:
ax = sns.barplot(
    data=df[df['Product'] == product[0],
    y='Ticket Type',
    x='Ticket Price Paid',
    hue='Year',  # Group bars by year
    hue_order=['2024', '2025']  # Ensure the legend and bar order
)

ax.set_title('Total Revenue By Ticket Type')
ax.set_xlabel('')
ax.set_ylabel('')

ax.xaxis.set_major_formatter(ticker.StrMethodFormatter('{x:,.0f}'))
ax.legend(
    #title='Year', 
    loc='lower right', bbox_to_anchor=(1, 0.5))

plt.show()